apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-nischal
  labels:
    env: rolly
subjects:
- kind: User
  name: nischal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-nischal
  apiGroup: rbac.authorization.k8s.io

