apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx:1.27
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:  
  - name: volume-storage
    persistentVolumeClaim: 
     claimName: mypvc #name of Persistent Volume Claim

