apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    ports:
    - containerPort: 80
    env:
    - name: firstname
      valueFrom:
        configMapKeyRef:
          name: config
          key: firstname
    - name: lastname
      valueFrom:
        configMapKeyRef:
          name: config
          key: lastname

