apiVersion: v1
kind: ReplicationController
metadata: # metadata for the ReplicationController itself
  name: replica-set
  labels:
    env: demo
spec: # spec for the ReplicationController
  replicas: 3 # number of replicas
  selector:
    env: demo # selector for matching pods with this label

  template:
    metadata:
      labels:
        env: demo
    spec: # spec for the pods
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 8000
