apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusbind-nischal
subjects:
- kind: User
  name: nischal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: clus-nischal
  apiGroup: rbac.authorization.k8s.io

