apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clus-nischal
  namespace: default
  labels:
    env: cluster
rules:
- apiGroups: ["apps"]
  resources: ['deployments']
  verbs: ["get", "watch"]
