apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clusdeploy
  template:
    metadata:
      labels:
        app: clusdeploy
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      nodeSelector:
        env: "worker1"



