apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: simple-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "200Mi"
    ports:
    - containerPort: 80
  nodeSelector:
    health: "true"
