apiVersion: v1
kind: Pod
metadata:
  name: tcp-live
  labels:
    name: tcp-live
spec:
  containers:
  - name: tcp-live
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 15
